name: Build and Deploy to Azure

env:
  AZURE_CONTAINER_REGISTRY_NAME: "clmkathyacr240218" #set this to the name of your Azure Container Registry
  AZURE_CONTAINER_REGISTRY: "clmkathyacr240218.azurecr.io" #container registry URI
  CONTAINER_NAME: "hello-world"
  RESOURCE_GROUP: "githubaction-demo-clmkathy"
  CLUSTER_NAME: "clmkathy-aks-cluster"
  DEPLOYMENT_MANIFEST_PATH: "kubernetes"

on:
  push: 
    branches: ["master"]
  workflow_dispatch: #manually trigger

permissions:
  contents: read

jobs:
  buildImage:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Docker Setup Buildx
  # You may pin to the exact commit or the version.
  # uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        uses: docker/setup-buildx-action@v3.0.0

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
    # Container registry username
          username: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
    # Container registry password
          password: ${{ env.AZURE_CONTAINER_REGISTRY_PASSWORD }}
    # Container registry server url
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ gitbub.sha }}
          file: ./Dockerfile
          
  deploy:
    runs-on: ubuntu-latest

    permissions:
       actions: read
       contents: read
       id-token: write

    environment: Production
    needs: [buildImage]

    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.1

        
